export enum HttpErrorCode {
	UnprocessableEntity = "UNPROCESSABLE_ENTITY",
	BadGateway = "BAD_GATEWAY",
	BadRequest = "BAD_REQUEST",
	Conflict = "CONFLICT",
	Forbidden = "FORBIDDEN",
	GatewayTimeout = "GATEWAY_TIMEOUT",
	NotFound = "NOT_FOUND",
	NotImplemented = "NOT_IMPLEMENTED",
	PayloadTooLarge = "PAYLOAD_TOO_LARGE",
	ServiceUnavailable = "SERVICE_UNAVAILABLE",
	TooManyRequest = "TOO_MANY_REQUEST",
	MethodNotAllowed = "METHOD_NOT_ALLOWED",
	Unauthorized = "UNAUTHORIZED",
	InternalError = "INTERNAL_ERROR",
}
